#pragma kernel CSMain

RWTexture2D<float4> Result;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    uint width, height;
    Result.GetDimensions(width, height);

    if (id.x >= width || id.y >= height)
        return;

    float u = (float) id.x / (float) width;
    float v = (float) id.y / (float) height;

    float4 color = float4(u, v, 0, 1);

    Result[id.xy] = color;
}